import "./globals.css";
import Header from "./Components/Common/Header";
import Footer from "./Components/Common/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">

         <Header/>
      

        {children}


        <Footer/>
        </body>
    </html>
  );
}
