name: next-deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      
      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: dist/
          retention-days: 7
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push only dist folder to deploy branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist          
          branch: deploy        
          clean: true
        